apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frc-ingress
spec:
  rules:
    - host: frc.systems
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
